apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::010526266250:role/eksctl-srikanth-nodegroup-srikanth-NodeInstanceRole-kVirlPBzx7jM
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - fresher
      userarn: arn:aws:iam::010526266250:user/fresher
      username: fresher
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-17T11:53:22Z"
  name: fresher
  namespace: kube-system
  uid: 59731f77-4559-4d77-9687-26d5442d391a